### ISSUE TITLE
Calibration data

### ISSUE THREAD

**Issue by tiagobbatalhao** [IBM/qiskit-sdk-py#11]
In older versions of the API, the returned result of a past experiment contained information about the device calibration at the moment that the experiment was performed. This seems to be missing from this version. The functions to get data about device calibration seem to work only with the most recent calibration data. 
It is useful to have a way to check the device calibration at some specific time in the past, especially at the time when a particular experiment was run. 
Why is that feature missing (or at least not as easily accessible as in previous versions)?

**Comment by pacomf** [comment]
Fixed on qiskit-api-py: https://github.com/IBM/qiskit-api-py/issues/25
